CREATE TABLE cash_card (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    balance DOUBLE NOT NULL,
    owner VARCHAR(255) NOT NULL
);

INSERT INTO cash_card (balance, owner) VALUES
(150.75, 'Alice Smith'),
(320.40, 'Bob Johnson'),
(50.00, 'Charlie Brown'),
(675.20, 'Diana Wilson'),
(245.90, 'Emma Davis');